server:
  port: 8000

graphql:
  servlet.mapping: /graphql

tmdb:
  apiURL: https://api.themoviedb.org/3
  imageBaseURL: https://image.tmdb.org/t/p/

logging:
  level:
    root: INFO
    com.example: DEBUG